package com.kernel.android.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0b6d36)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF9df6b0)
val md_theme_light_onPrimaryContainer = Color(0xFF00210a)
val md_theme_light_secondary = Color(0xFF506352)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd3e8d3)
val md_theme_light_onSecondaryContainer = Color(0xFF0e1f12)
val md_theme_light_tertiary = Color(0xFF006972)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF80f3ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f23)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdde4da)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF717970)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF82d996)
val md_theme_dark_onPrimary = Color(0xFF003917)
val md_theme_dark_primaryContainer = Color(0xFF005324)
val md_theme_dark_onPrimaryContainer = Color(0xFF9df6b0)
val md_theme_dark_secondary = Color(0xFFb7ccb7)
val md_theme_dark_onSecondary = Color(0xFF233426)
val md_theme_dark_secondaryContainer = Color(0xFF394b3b)
val md_theme_dark_onSecondaryContainer = Color(0xFFd3e8d3)
val md_theme_dark_tertiary = Color(0xFF4dd8e6)
val md_theme_dark_onTertiary = Color(0xFF00363b)
val md_theme_dark_tertiaryContainer = Color(0xFF004f56)
val md_theme_dark_onTertiaryContainer = Color(0xFF80f3ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c9bf)
val md_theme_dark_outline = Color(0xFF8b9389)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val separator = Color(0x908D8D8D)
val progress_background = Color(0x75000000)

val seed = Color(0xFF295133)
val error = Color(0xFFba1b1b)